(package "reel"
         "0.1.0"
         "An HTTP client for Emacs built in Rust")

(website-url "https://github.com/rfaulhaber/reel")
(keywords "lisp")

(package-file "reel.el")

(files
    "*.el"
    "libreel.dylib"
    "libreel.so"
    "libreel.dll"
    "out"
    "Cargo.toml"
    "Cargo.lock"
    "src")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "melpa")

(depends-on "emacs" "27.1")
