name: build
run-name: ${{ github.actor }} build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]

defaults:
  run:
    shell: nu {0}


jobs:
  ci:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        emacs-version:
          - 28.2
          - 29.2
          - snapshot
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: hustcer/setup-nu@main
        with:
          version: "*"
      - uses: extractions/setup-just@v2
      - uses: jcs090218/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}
      - uses: emacs-eask/setup-eask@master
        with:
          version: 'snapshot'
      - name: Compile module
        run: |
          just build
          ls
      - name: install pueue for tests
        run: |
          cargo install --locked pueue
      - name: Run tests
        run: |
          just test
