name: build
run-name: ${{ github.actor }} build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]


jobs:
  ci:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        emacs-version:
          - 26.3
          - 27.2
          - 28.2
          - 29.1
          - snapshot
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: jcs090218/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - uses: emacs-eask/setup-eask@master
        with:
          version: 'snapshot'
      - name: Compile module
        run: |
          cargo build --release
          mv ./target/release/libreel.* .
      - name: Eask install
        run: |
          eask install
