name: build
run-name: ${{ github.actor }} build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]


jobs:
  ci:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        emacs-version:
          - 28.2
          - 29.2
          - snapshot
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: jcs090218/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - uses: emacs-eask/setup-eask@master
        with:
          version: 'snapshot'
      - name: Compile module
        run: |
          cargo build
          echo "Moving module"
          mv ./target/debug/libreel.* .
          eask install
      - name: Run tests
        run: |
          docker run -d --rm --name reel-test -p 8080:80 kennethreitz/httpbin
          sleep 5s
          eask test buttercup
          docker stop reel-test
